var a = true;
var b = false;
var n = 45;
var s = "hello world";
var se = 'hello world';
console.log(a);
console.log(b);
console.log(n);
console.log(s);
console.log(se);
console.log("got are new " + ("" + se));
console.log("hi" + "\n" + "age");
var list = [1, 2, 3, 4];
console.log(list + "\n" + list[0]);
var tupe = [1, "ali"];
var tupeList = [1, "ammu", 2, "annu"];
console.log("tuple--->" + tupe);
console.log(tupe[0]);
console.log(tupe[1]);
console.log("tupleList---->" + tupeList);
var color;
(function (color) {
    color[color["bule"] = 0] = "bule";
    color[color["green"] = 1] = "green";
    color[color["red"] = 2] = "red";
})(color || (color = {}));
console.log(color);
console.log(color[2]);
console.log(color.green);
var e = color.green;
console.log("--------" + e);
var un = "say,hi";
console.log(un);
un = 35;
console.log(un);
var ab = 676;
ab = "fdg";
console.log(ab);
